# Server configurations
server:
  port: 8080

# Database configurations
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store?characterEncoding=utf-8
    username: root
    password: 555555
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true