# Server configurations
server:
  port: 8080

# Database configurations
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store?characterEncoding=utf-8
    username: root
    password: 555555
  redis:
    host: 127.0.0.1
    port: 6379
    password: f8c5a616-a0ac-40af-a283-052746649c69
    database: 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.qq.com
    port: 587
    username: co-blog@qq.com
    password: qgiegwujfquqbjfd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  devtools:
    restart:
      enable: true